services:
  - type: web
    name: realestate-prediction
    env: python
    region: oregon
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn realestate.wsgi:application --workers 2 --threads 4 --timeout 60
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com
    healthCheckPath: /
    autoDeploy: true
    plan: free